apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-backup-pv-claim
  namespace: github-backup
  labels:
    app: github-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
